name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master", "principal" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nemotron-mobile-app-corrigido

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependências
        run: npm install

      - name: Criar projeto Android
        run: npx cap add android

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Permissão Gradle
        run: chmod +x android/gradlew

      - name: Gerar APK Debug
        run: cd android && ./gradlew assembleDebug

      - name: Enviar APK para download
        uses: actions/upload-artifact@v4
        with:
          name: Nemotron-Chat-APK
          path: nemotron-mobile-app-corrigido/android/app/build/outputs/apk/debug/app-debug.apk
